ARG GOLANG_VERSION

FROM golang:$GOLANG_VERSION-alpine

RUN echo $GOLANG_VERSION
RUN apk update && apk add --no-cache git bash make gcc libc-dev librdkafka-dev pkgconf openssh netcat-openbsd curl kafkacat
RUN go install golang.org/x/lint/golint@latest
RUN mkdir -p /transformer/tests

WORKDIR /transformer/tests

COPY . .